name: Release Build

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            cgo: 0
          - goos: linux
            goarch: arm64
            cgo: 0
          - goos: windows
            goarch: amd64
            cgo: 0
          - goos: darwin
            goarch: amd64
            cgo: 0
          - goos: darwin
            goarch: arm64
            cgo: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: ${{ matrix.cgo }}
        run: |
          mkdir -p dist/cs_${{ matrix.goos }}_${{ matrix.goarch }}
          if [ "${{ matrix.goos }}" = "windows" ]; then
            go build -tags "sqlite_omit_load_extension sqlite_static" -o "dist/cs_${{ matrix.goos }}_${{ matrix.goarch }}/cs.exe" -v
          else
            go build -tags "sqlite_omit_load_extension sqlite_static" -o "dist/cs_${{ matrix.goos }}_${{ matrix.goarch }}/cs" -v
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cs_${{ matrix.goos }}_${{ matrix.goarch }}
          path: dist/cs_${{ matrix.goos }}_${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Create release archives
        run: |
          cd dist
          for dir in */; do
            platform=${dir%/}
            tar -czf "${platform}.tar.gz" "$platform"
          done

      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          cd dist
          gh release create "$VERSION" *.tar.gz \
            --title "Release $VERSION" \
            --notes "Release $VERSION" \
            --draft=false