name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib gcc-mingw-w64

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 1
        run: |
          output_name="cs"
          if [ "${{ matrix.goos }}" = "windows" ]; then
            output_name="cs.exe"
          fi
          go build -o "dist/cs_${{ matrix.goos }}_${{ matrix.goarch }}/$output_name" -v

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cs_${{ matrix.goos }}_${{ matrix.goarch }}
          path: dist/cs_${{ matrix.goos }}_${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Create release archives
        run: |
          cd dist
          for dir in */; do
            platform=${dir%/}
            tar -czf "${platform}.tar.gz" "$platform"
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 