name: Release Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            cgo: 1
          - goos: linux
            goarch: arm64
            cgo: 1
          - goos: windows
            goarch: amd64
            cgo: 1
          - goos: darwin
            goarch: amd64
            cgo: 0
          - goos: darwin
            goarch: arm64
            cgo: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Install dependencies
        if: matrix.goos == 'linux' || matrix.goos == 'windows'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib gcc-mingw-w64 gcc-aarch64-linux-gnu

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: ${{ matrix.cgo }}
        run: |
          mkdir -p dist/cs_${{ matrix.goos }}_${{ matrix.goarch }}
          if [ "${{ matrix.goos }}" = "windows" ]; then
            if [ "${{ matrix.goarch }}" = "amd64" ]; then
              export CC=x86_64-w64-mingw32-gcc
            fi
            go build -o "dist/cs_${{ matrix.goos }}_${{ matrix.goarch }}/cs.exe" -v
          elif [ "${{ matrix.goos }}" = "linux" ] && [ "${{ matrix.goarch }}" = "arm64" ]; then
            export CC=aarch64-linux-gnu-gcc
            go build -o "dist/cs_${{ matrix.goos }}_${{ matrix.goarch }}/cs" -v
          else
            go build -o "dist/cs_${{ matrix.goos }}_${{ matrix.goarch }}/cs" -v
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cs_${{ matrix.goos }}_${{ matrix.goarch }}
          path: dist/cs_${{ matrix.goos }}_${{ matrix.goarch }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: dist

      - name: Create release archives
        run: |
          cd dist
          for dir in */; do
            platform=${dir%/}
            tar -czf "${platform}.tar.gz" "$platform"
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.tar.gz
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}